filebeat.inputs:
  - type: log
    enabled: true
  {% if logType == "json" %}
json.keys_under_root: true
  {% endif %}
paths:
  - {{logLocation}}
fields:
  appName: {{COMPONENT}}
  env: {{ENV}}
  logType: {{logType}}

  {% if COMPONENT == "shipping" %}
multiline.type: pattern
multiline.pattern: '^[0-9]'
multiline.negate: true
multiline.match: after
  {% endif %}

output.logstash:
  hosts: ["172.31.85.8:5044"]

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1


# =================================== Kibana ===================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.
setup.kibana:


# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
