apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-cm
data:
  MONGO_URL: 'mongodb://admin1:roboshop1@roboshop-docdb-prod.cluster-ciqb6xvrbz0q.us-east-1.docdb.amazonaws.com:27017/catalogue?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
data:
  MONGO_URL: 'mongodb://admin1:roboshop1@roboshop-docdb-prod.cluster-ciqb6xvrbz0q.us-east-1.docdb.amazonaws.com:27017/user?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false'
  REDIS_HOST: redis-prod.roboshop.internal

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-cm
data:
  CATALOGUE_HOST: catalogue-roboshop
  REDIS_HOST: redis-prod.roboshop.internal

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-cm
data:
  DB_HOST: mysql-prod.roboshop.internal
  CART_ENDPOINT: cart-roboshop

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-cm
data:
  CART_HOST: mysql-prod.roboshop.internal
  USER_HOST:
  